### ISSUE TITLE
Custom Command Error

### ISSUE THREAD

**Issue by joharhussain** [inFullMobile/videokit-ffmpeg-android#1]
Thanks for this nice interface of [FFMPEG](https://www.ffmpeg.org/) for android. I am trying to execute custom command i.e. adding an image overlay on a video. It always fails. Here is mt code

`final Command command = videoKit.createCommand()`
                `.overwriteOutput()`
                `.addInputPath(path)`
                `.addInputPath("/sdcard/logo.png")// logo.png exists on sdcard.`
                `.addOutputPath(path + POSTFIX)`
                `.copyVideoCodec()`
                `.addExperimentalFlag()`
                `.addCustomCommand("-filter_complex overlay")`
                `.build();`

If there is any mistake please let me know. thanks

**Comment by IljaKosynkin** [comment]
Hello @joharhussain 
Please note that addInputPath is supposed to be used once to provide actual path to processed video. Yes, I should admit that name doesn't reflect it quite well, so I will try to adjust it as soon as possible. 
Can you give whole ffmpeg command that you want to execute? I mean CLI command ("ffmpeg -i path" and so on), so we can break it down.

**Comment by joharhussain** [comment]
@IljaKosynkin  Thanks for your reply. I have to add an image overlay on a selected video.  Below is the complete command 

`ffmpeg -i /sdcard/movie.mp4 -i /sdcard/logo.png -filter_complex overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2 /sdcard/output.mp4`

You can check [this](https://www.ffmpeg.org/ffmpeg-filters.html#overlay-1) for reference. Thanks

**Comment by IljaKosynkin** [comment]
@joharhussain 
Ok, I see.
First of all I didn't really assumed situation with two input, so as current solution I can suggest you to put .addCustomCommand("-i /sdcard/logo.png") just after .addInputPath(path)
So I would construct whole command as follow:
```java
final Command command = videoKit.createCommand()
    .overwriteOutput()
    .addInputPath(path)
    .addCustomCommand("-i /sdcard/logo.png")
    .addOutputPath(path + POSTFIX)
    .addCustomCommand("-filter_complex overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2")
    .addExperimentalFlag()
    .build();
```
Try it and let me know the result please :) Also, did you turn on logging on VideoKit? It can be helpfull

**Comment by joharhussain** [comment]
@IljaKosynkin This command works successfully. Thanks. I was trying to add image file via `addInputPath` method or combine with custom command i.e. `-i /sdcard/logo.png -filter_complex overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2`.
Yes I turned on logging on VideoKit.

Below are the logs.

```
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: ffmpeg
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: -y
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: -i
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: /storage/emulated/0/movie.mp4
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: -i
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: /sdcard/logo.png
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: -filter_complex
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: -strict
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: -2
09-29 16:39:34.466 20043-30028/ffmpeg.videokit.sample I/Videokit: Option: /storage/emulated/0/movie.mp4result_p.mp4
09-29 16:39:55.654 20043-30028/ffmpeg.videokit.sample I/Videokit: 2609 frames successfully decoded, 0 decoding errors
09-29 16:39:55.672 20043-30028/ffmpeg.videokit.sample I/Videokit: Main ended with status 0
                                                                  
                                                                  --------- beginning of system
```

**Comment by IljaKosynkin** [comment]
@joharhussain 
I suspect that this .addExperimentalFlag() should always be at the end and it also could be the problem with your command. I didn't have time to prove it, unfortunately, and FFmpeg doesn't have greatest debugging capabilities, but you can take it as a rule of thumb: addExperimentalFlag() should be always just before .build(). I will try to mention it in current documentation and then do work-around in next release.
So all works fine now? Did you check video?

**Comment by joharhussain** [comment]
@IljaKosynkin 
It would be great to add this in documentation. I have checked the video it works fine but this is reducing the video quality than original one.

**Comment by IljaKosynkin** [comment]
@joharhussain 
I believe there is option that allows you to convert video without loosing of quality, but by the cost of processing time obviously. I don't remember exactly which one - look over documentation of FFmpeg please :)
So can I close this ticket now or you any other problems?
