### ISSUE TITLE
Apk size increase.

### ISSUE THREAD

**Issue by pavel-corsaghin** [inFullMobile/videokit-ffmpeg-android#15]
Hi, Thank you for making awesome library but my app size increase from 7mb to 34mb after added this library. How can i solve it?

**Comment by IljaKosynkin** [comment]
@pavel-corsaghin 
If apk size is really concern for you - first of all, make sure that you're using split-abi gradle function. If actual apk size (on device) still will be too big for you - you can make your own version of VideoKit building FFMpeg with --enable-small flag. Note that it will sacrifice some performance in order to make final .so file size smaller.

**Comment by pavel-corsaghin** [comment]
Hi, Thank you for reply. I will try it, please don't close this issues now. Thanks again and sorry for my English.

**Comment by pavel-corsaghin** [comment]
Hi, could you tell me difference between compile and use .so files and only one static file ffmpeg?

**Comment by IljaKosynkin** [comment]
@pavel-corsaghin 
Sorry, didn't get what do you mean by "static" file. Do you mean binary of FFmpeg?

**Comment by pavel-corsaghin** [comment]
Hi, in some projects i see people using only one file named ffmpeg which localed in assets folder, in some projects they using ffmpeg.aar file in libs folder, in your project you are using .so files in jniLibs folder. And i don't know what is difference between those ways

**Comment by IljaKosynkin** [comment]
@pavel-corsaghin 
Assets folder - ffmpeg binary which is being executed with Runtime.getRuntime().exec() (basically, command line). Not clean way to do it, also not really good for support of particular architectures, but it might work. 
Actually, VideoKit is .aar file (android library), which is using .so files in it's way.
You can use .so files from ffmpeg directly if you would write JNI wrapper for them. VideoKit is providing this wrapper and Java interface out-of-the box, but you can write everything by yourself, if you want to.

**Comment by pavel-corsaghin** [comment]
Thank you very much. I follow your tutorial and have created .so file. But their size is too big (the size of my armabi/lib folder is 79mb) even i have used --enable-small. End i see your armabi only 11mb. Can you tell me How can you create a low capacity files? and they have all features of ffmpeg? i am planing to use ffmpeg to trim, crop, rotate, add text, add image, combine, merge.. videos. This is my configuration (based on your)
#!/bin/bash
export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARENT="$(dirname "${DIR}")"
export NDK="$(dirname "${PARENT}")"
export PATH="$PATH:$NDK"
export PROJECT_JNI="$(dirname "${NDK}")/JNI/app/jni"
export PROJECT_LIBS="$(dirname "${NDK}")/JNI/app/libs"
export COMMON="--disable-static --enable-shared --disable-programs --disable-doc --enable-small --enable-protocol=file"
export CONFIGURATION="--disable-everything --enable-ffmpeg --enable-avcodec --enable-avformat --enable-avutil --enable-swresample --enable-avfilter --enable-swscale --enable-filter=aresample --enable-filter=crop --enable-filter=scale --enable-filter=transpose --enable-protocol=file --enable-libvorbis --enable-libvpx --enable-decoder=aac --enable-decoder=amrnb --enable-decoder=amrwb --enable-decoder=flac --enable-decoder=mp3 --enable-decoder=libvorbis --enable-decoder=adpcm_ima_wav --enable-decoder=h263 --enable-decoder=h263p --enable-decoder=h264 --enable-decoder=mpeg4 --enable-decoder=libvpx_vp8 --enable-demuxer=concat --enable-demuxer=mov --enable-demuxer=mpegts --enable-demuxer=webm --enable-demuxer=matroska --enable-encoder=libvorbis --enable-encoder=libvpx_vp8 --enable-muxer=webm"
#export ADDI_CFLAGS="pass here additional c-flags like include I/path"
#eport ADDI_LDFLAGS="pass here additional flags like include L/path for linker"

./build_armeabi.sh
#./build_armeabi-v7a.sh
#./build_arm64-v8a.sh
#./build_mips.sh
#./build_x86.sh

**Comment by IljaKosynkin** [comment]
@pavel-corsaghin 
Do you mean armeabi inside FFmpeg/android or final version builded with NDK?

**Comment by pavel-corsaghin** [comment]
My final version builded with NDK have 79mb of size (7 .so files). Your .so files located in videokit-ffmpeg-android/videokit/src/main/jniLibs/armeabi/ have only 11mb (8 .so files include yor libvideokit.so) and when i use it in my project with split-abi as you guided me above my file size increase only 5mb, this is awesome but i want to know how can you create those files and they have fully ffmpeg features or not (as i read on stackoverflow when compile ffmpeg we can disable some features for reduce .so files size)

**Comment by IljaKosynkin** [comment]
@pavel-corsaghin I would suggest you to set configuration to this:
"--disable-static --disable-programs --disable-doc --enable-shared --enable-protocol=file --enable-pic --enable-small"
It should provide all free features of FFmpeg. Note that there are some features licensed under GPL, not LGPL

**Comment by pavel-corsaghin** [comment]
I have tried but still can not create a small files like yours, so please allow me to use your files in my project.Thank you again for creating a great and handy library for beginners like me.

**Comment by IljaKosynkin** [comment]
@pavel-corsaghin so I can close this issue now?
