### ISSUE TITLE
failvideokit: Code:1002

### ISSUE THREAD

**Issue by HD-AD** [inFullMobile/videokit-ffmpeg-android#17]
I get code 1002 error (Main ended with status 1002) when exporting larger (longer in length) videos. Everything works perfectly when exporting shorter videos.

Here is where the error comes from:

@Override
    public void onFailure(int returnCode) {
    Log.d("failvideokit","Code:"+returnCode);
    }

This happens when I try to implement trimming with the following;

.customCommand("-ss "+valueLeft)
.customCommand("-to "+valueRight)

Any idea why this error is only showing on longer videos?

**Comment by IljaKosynkin** [comment]
@HD-AD 
As I see in the error codes list, this error code indicates that you provided incorrect time. 
`int64_t parse_time_or_die(const char *context, const char *timestr,
                          int is_duration)
{
    int64_t us;
    if (av_parse_time(&us, timestr, is_duration) < 0) {
        if (loglevel > 0) 
        	LOGI("Invalid %s specification for %s: %s\n",
               is_duration ? "duration" : "date", context, timestr);
        exit_program(1002);
    }
    return us;
}`

Do you have logs in adb terminal?

**Comment by HD-AD** [comment]
I got it fixed, the problem was caused by passing invalid time format. Thank you for getting back to me.
