### ISSUE TITLE
-crf option not working

### ISSUE THREAD

**Issue by HD-AD** [inFullMobile/videokit-ffmpeg-android#19]
I'm am trying the following commands but I get a error 2041 which apparently is related to "invalid sample description";
```
final Command command = videoKit.createCommand()
                          .inputPath(mVideoUri.toString().replace("file://",""))
                          .inputPath(newBackgroundBitmap.getPath())
                          .outputPath(directoryToStore+"/"+lastSaved+mp)
                          .customCommand("-filter_complex [1:v][0:v]scale2ref=iw:ih[ovr][base];[ovr]colorchannelmixer=aa=0.7[ovrl];[base][ovrl]overlay[v] -map [v]")
                          .customCommand("-crf "+"23")
                          .customCommand("-ss "+valueLeft)
                          .customCommand("-t "+valueDur)
```

I also tried increasing the bitrate with ```.limitVideoBitrate("6000k") ``` but I keep getting back low bitrates.

**Comment by HD-AD** [comment]
I asked a question on superuser.com about this issue. 

Here is the link ;
https://superuser.com/questions/1222790/android-increasing-bitrate-with-ffmpeg

The main problem I am having is that I want to increase the bitrate value when exporting the video.

**Comment by HD-AD** [comment]
I still haven't resolved this issue, Just to add more detail, here is the command I am using:
```
final VideoKit videoKit = new VideoKit();

    final Command command = videoKit.createCommand()
         .overwriteOutput()
        .inputPath(mVideoUri.toString().replace("file://",""))
         .inputPath(newBackgroundBitmap.getPath())
        .outputPath(directoryToStore+"/"+lastSaved+mp)

        .customCommand("-filter_complex [1:v][0:v]scale2ref=iw:ih[ovr][base];[ovr]colorchannelmixer=aa=0.7[ovrl];[base][ovrl]overlay[v] -map [v]")
        .customCommand("-ss "+valueLeft)
        .customCommand("-t "+valueDur)
```
When I try to use ```.customCommand("-crf "+"20")``` I get the error, if I don't use it the bitrate is reduced drastically. If this option is not available with this library, I am looking for a way to retain the bitrate.

PLEASE CAN SOMEONE RESPOND?

**Comment by IljaKosynkin** [comment]
@HD-AD 
-crf is option provided by libvpx-vp8 encoder, which is non-free component as far as I know. VideoKit doesn't contain any such components since it's licensed under LGPL. Is you want to any of GPL licensed parts of FFmpeg you will have to rebuilt VideoKit with FFmpeg .so files which are linked with those components.

**Comment by HD-AD** [comment]
Thank you for replying, I first used this library (http://writingminds.github.io/ffmpeg-android/) which includes this option (But ffmpeg is outdated). So correct me if I am wrong libX264 is not free to use?

**Comment by HD-AD** [comment]
I just read this which states that it is free to use https://trac.ffmpeg.org/wiki/Encode/VP8

**Comment by HD-AD** [comment]
https://www.webmproject.org/tools/ they also state that it is free for use. To enable it in ffmpeg, when compiling, ```--enable-libvpx``` should be added. Adding this to this library will help a lot of people including myself. Would you please consider this?

**Comment by IljaKosynkin** [comment]
@HD-AD 
Well, I checked it one more time and it seems that libvpx-vp8 is licensed under BSD which is theoretically LGPL compatible license as stated here:
http://www.ffmpeg.org/doxygen/3.0/md_LICENSE.html
However, libx264 is GPL licensed so it cannot be provided as part of VideoKit.
I will think about adding libvpx-vp8 to the project

**Comment by HD-AD** [comment]
Ok thank you for considering adding libvpx-vp8, I have been struggling with this for more than a month. This will really mean so much.

**Comment by HD-AD** [comment]
@IljaKosynkin Can you please let me know when you decided if you will add  libvpx-vp8. I can't continue with this project without knowing.

**Comment by IljaKosynkin** [comment]
@HD-AD 
I think I will add it eventually, however, I cannot make any promises when it will be ready. If you need it ASAP I would suggest you to rebuild VideoKit with libvpx-vp8 and use it instead of version distributed via Maven.

**Comment by HD-AD** [comment]
I rebuild with libvpx-vp8 and problem is fixed:)

**Comment by vxhviet** [comment]
Dear @HD-AD , 

I've encountered the same problem, would you mind sharing your ffmpeg build or giving the instruction how to rebuild ffmpeg with libvpx-vp8 included please?

**Comment by vxhviet** [comment]
@IljaKosynkin ,

Hi could you provide some information how can I include  libvpx-vp8 into a new build. I've tried to include it in the `COMMON` in `build_all.sh` like this:

```
export COMMON="--disable-static --disable-programs --disable-doc --enable-shared --enable-protocol=file --enable-pic --enable-small --enable-libvpx"
```

but always get hit with `libvpx decoder version must be >=0.9.1` error (please see [my detail report](https://medium.com/@vxh.viet/dear-ilia-kosynkin-e3b8f81ed3ed) in your medium article). 

Is it the correct way to enable libvpx-vp8 or should it be included into ffmpeg build [like this](https://stackoverflow.com/questions/11003420/ffmpeg-unable-to-find-encoder-libvpx)?

**Comment by samyakjain** [comment]
hey @IljaKosynkin I need support of -crf . How can i rebuild videokit ? Please help. 

@HD-AD Can you help on this?
