### ISSUE TITLE
Not able to lower bitrate?

### ISSUE THREAD

**Issue by jayk140** [inFullMobile/videokit-ffmpeg-android#20]
Hello - first, thank you so much for this library! 

Can you please review my custom command below? I am not able to reduce the bitrate of my video. I am able to successfully change the resolution/size of the video using `-filter:v scale` command.

`                final Command command = videoKit.createCommand()
                        .overwriteOutput()
                        .inputPath(path)
                        .outputPath(newPath)
                        .customCommand("-filter:v scale=1080:-1" + " -b:v 512k")
                        .experimentalFlag()
                        .build();`

**Comment by jayk140** [comment]
I also tried specifying a codec in addition to the bitrate: `-c:v libx264 -b:v 512k` but it still does not reduce bitrate.

**Comment by jayk140** [comment]
When I try to run this custom command: `.customCommand("-b:v 200k -c:v libx264 -vf scale=640:360 -c:a aac -b:a 128k")` I get an error code 3018 which corresponds to this line in ffmpeg: https://github.com/FFmpeg/FFmpeg/blob/master/ffmpeg_opt.c#L586. Do you know what this error means?

**Comment by jayk140** [comment]
I've also tried to simply add `.limitVideoBitrate("512k")` to the command without a customCommand, but the resulting video's bitrate is not changed.

Any help would be greatly appreciated. My goal is to reduce the file size of videos coming from Android camera/gallery.

**Comment by IljaKosynkin** [comment]
@jayk140 
The command seems fine to me.
Video gets processed, right? There are no errors, you get new file that just lacking bitrate reduction or are there another problems?

**Comment by jayk140** [comment]
@IljaKosynkin  Yes, the `.limitVideoBitrate("512k")` command works fine with no errors. The logs says `I/Videokit: 810 frames successfully decoded, 0 decoding errors` `I/Videokit: Main ended with status 0`.

However, the new file's bitrate is unchanged.

Again, thanks so much for this library and I greatly appreciate your help!

**Comment by IljaKosynkin** [comment]
@jayk140 
Can you provide the format of the file? Did you try to limit this video bitrate with standard desktop version of FFmpeg?

**Comment by jayk140** [comment]
@IljaKosynkin 

Video format: Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 16930 kb/s, 29.96 fps, 30 tbr, 90k tbn.

Audio format: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default).

Yes I was able to reduce bitrate with FFMPEG on my computer with the command: `ffmpeg -i vid.mp4 -b:v 200k new.mp4`

**Comment by IljaKosynkin** [comment]
@jayk140 
Hmm, I'm not entirely sure that h264 is supported. Can you check on other formats?

**Comment by jayk140** [comment]
@IljaKosynkin 

Hm, do you know how I can test with other formats?

The video in my app is coming when the user chooses a video from their gallery and it is in h264 by default.

**Comment by IljaKosynkin** [comment]
@jayk140 
I will check this out if I will a bit of spare time.  In meantime I would suggest to try some extremely low value like 20k and see how it would behave.

**Comment by jayk140** [comment]
@IljaKosynkin 

It seems when I reduce the resolution/size enough, for example `-filter:v scale=500:-1`, the bitrate is also reduced, from around 4000 kb/s to 1000 kb/s. But still actually trying to reduce bitrate with `. limitVideoBitrate` or `-b:v` command seems to have no effect.

Reducing the scale also reduces the video file size sufficient for my purposes. However, the operation takes very long. It takes about 3 and a half minutes for a 1 minute video. Do you know how I can improve the speed?

I tried adding the preset flag: `-preset veryfast -filter:v scale=500:-1` i get the error code 2041 which corresponds to the line `duration += ist->max_pts - ist->min_pts;` in ffmpeg code. Not sure what it means.

**Comment by jayk140** [comment]
@IljaKosynkin 

Would you know why I'm getting 2014 error when I run this command: `"-filter:v scale=500:890 -preset fast"`? I run the same command on my desktop FFMPEG and it works fine.

**Comment by IljaKosynkin** [comment]
@jayk140 preset is a part of libx264 which is not included as part of VideoKit since it's GPL licensed.
As for speed, if it's critical for you, I would suggest to use MediaCodec, not FFmpeg.

**Comment by jayk140** [comment]
@IljaKosynkin 

I looked into MediaCodec but was having a hard time understanding how it works. Would you be able to give me some guidance or point me to some online tutorials on how to use MediaCodec to reduce a video's file size?

Sorry I know I'm asking you for a lot, I really appreciate all your help.

**Comment by IljaKosynkin** [comment]
@jayk140 
I have done such task quite a while ago, check out this:
https://stackoverflow.com/questions/36808806/android-fast-video-processing
UPDATE section.
