### ISSUE TITLE
video compression result only 1 second

### ISSUE THREAD

**Issue by j-elmer123** [inFullMobile/videokit-ffmpeg-android#30]
Hi @IljaKosynkin and @kolipass , I want to ask how to compress video file properly?
I got `inputPath = "/storage/emulated/0/BDRC/BDRC/video.mp4"`
and I want to overwrite output, so this is what I did.

```kotlin
val videoKit = VideoKit()
val command = videoKit.createCommand()
        .overwriteOutput()
        .inputPath(inputPath)
        .outputPath(inputPath)
        .copyVideoCodec()
        .experimentalFlag()
        .build()

val result = AsyncCommandExecutor(command, object: ProcessingListener {
    override fun onSuccess(path: String?) {
        Log.e("SUCCESS", "COMPRESSING")
    }

    override fun onFailure(returnCode: Int) {
        Log.e("FAILURE", "COMPRESSING")
    }
}).execute()
```

but the result always 1 second video even though I record for 10 seconds. Can you explain what is wrong, please? I want to understand how this library works.

Regards,
Elmer

**Comment by surabhiverma1** [comment]
Facing same issue,video is compressed by 1 sec and size is not reduced.Have you figured out the issue?

**Comment by j-elmer123** [comment]
@surabhiverma1 at the end of the day I use https://github.com/WritingMinds/ffmpeg-android-java

**Comment by surabhiverma1** [comment]
I tried with writing mind library

private void versionFFmpeg() {
    FFmpeg.getInstance(this).execute(new String[]{ "-y","-i" ,"/storage/emulated/0/big_buck_bunny.mp4","-crf", "20", "-preset", "faster",  "-c", "copy","/storage/emulated/0/big_buck_bunnycompressed.mp4"}, new ExecuteBinaryResponseHandler() {
        @Override
        public void onSuccess(String message) {
                    Timber.d(message);
        }

        @Override
        public void onProgress(String message) {
            Timber.d(message);
                 }
    });

}

Still its not compressing the video . Is there any error in command.
